spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  application:
    name: catsInfo
  datasource:
    url: jdbc:postgresql://localhost:5433/owners
    username: owners_user
    password: owners_password
    driverClassName: org.postgresql.Driver

server:
  port: 8083